import type { Metadata } from "next";
import { DM_Sans, Inter } from "next/font/google";
import "@ui/styles/globals.css";
import { QueryProvider } from "@/lib/providers/QueryProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter}  antialiased`}>
        <QueryProvider>{children}</QueryProvider>
      </body>
    </html>
  );
}
